language: ruby
script: 'script/ci'
sudo: false

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby

matrix:
  allow_failures:
- rvm: jruby

cache:
  - bundler

before_install:
  - rvm get latest
  - gem install bundler

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9ca8d56f4d3a17425b18
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
